[project]
name = "billing-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.10.12",
    "dagster-webserver>=1.10.12",
]
